# Generated by Django 5.2.8 on 2025-11-26 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('especie', models.CharField(max_length=160)),
                ('raza', models.CharField(max_length=160)),
                ('color', models.CharField(max_length=160)),
                ('fecha_nacimiento', models.DateTimeField(max_length=160)),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=5, max_length=160)),
                ('nombre_duenio', models.CharField(max_length=160)),
                ('telefono_duenio', models.CharField(max_length=160)),
                ('email_duenio', models.CharField(max_length=160)),
                ('estado', models.CharField(max_length=160)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
