# Generated by Django 5.2.8 on 2025-11-26 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pets',
            name='fecha_nacimiento',
            field=models.DateField(max_length=160),
        ),
    ]
